title = "Custom Gitleaks Rules"

[[rules]]
id = "terraform-secrets"

description = "Detect Terraform Secrets"

regex = '''(?i)(password|secret|client_secret|token|access_key)\s*=\s*".+"'''

tags = ["terraform", "security"]