name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello GitHub Actions"

      - name: Print Date
        run: date