name: Terraform CI

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

  pull_request:
    branches:
      - main
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Production

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1

      - run: terraform version

      - run: terraform fmt -check -recursive

      - run: terraform init -backend=false

      - run: terraform validate